version: "3.8"

services:
    neo4j:
        container_name: neo4j_gdb
        image: neo4j:4.3.0-enterprise
        restart: always
        volumes: 
            - ./neo4j_data/data:/data
            - ./neo4j_data/import:/import
            - ./neo4j_data/plugins:/plugins
            - ./neo4j_data/conf:/conf
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            #- NEO4J_AUTH=neo4j/letmein
            - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
            - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_dbms_memory_pagecache_size=8G
            - NEO4j_dbms_memory_heap_initial__size=8G
            - NEO4J_dbms_memory_heap_max__size=16G

    jupyterlab:
        container_name: jupyter_gs
        build: ./notebooks
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/work
        links:
            - neo4j
        
    
    # js-graphql-backend:
    #     container_name: js_graphql
    #     build: ./jsgql-backend
    #     ports:
    #         - "4001:4001"
    #     links:
    #         - neo4j
    #     depends_on: 
    #         - neo4j

    # next-frontend:
    #     container_name: next_react
    #     build: ./next-frontend
    #     ports:
    #         - "3000:3000"
    #     links:
    #         - js-graphql-backend
    #     depends_on: 
    #         - js-graphql-backend
        
    
