version: "3.8"

services:
    neo4j:
        container_name: neo4j_gdb
        image: neo4j:4.3.0-enterprise
        restart: always
        volumes: 
            - ./neo4j_data:/data
            - ./neo4j_data:/var/lib/neo4j/import
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            #- NEO4J_AUTH=neo4j/letmein
            - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
            - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
            - NEO4J_apoc.import.file.enabled=true
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_dbms_memory_pagecache_size=8G
            - NEO4j_dbms_memory_heap_initial__size=8G
            - NEO4J_dbms_memory_heap_max__size=16G

    pgdb:
        container_name: postgres_sqldb
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=${PGDB_USER}
            - POSTGRES_PASSWORD=${PGDB_PASSWORD}
            - POSTGRES_DB=${PGDB_NAME}

    pgadmin:
        container_name: postgres_sql_admin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
        - 5050:80
        depends_on:
        - pgdb

    # rest-api:
    # graphql-api:
    # frontend:
    
